### ISSUE TITLE
deepValueEqual infinite recursion with recursive map types

### ISSUE THREAD

**Issue by stewi1014** [maxatome/go-testdeep#101]
I've found an infinite recursion case with go-testdeep. It's a bit contrived I know; I was actually trying to break things. I'm currently developing an encoding library and trying to break it with test cases galore. Interestingly enough encoding/gob, reflect.DeepEqual (fixed in go1.15), and every 3rd party library I've found suffers from this same issue.

If given a map containing a struct that contains the same map, deepValueEqual recuses infinitely.

This test case reproduces the issue
```go
func TestEqualRecursMap(t *testing.T) {
	gen := func() interface{} {
		type S struct {
			Map map[int]S
		}

		m := make(map[int]S)
		m[1] = S{
			Map: m,
		}

		return m
	}

	checkOK(t, gen(), gen())
}
```

Thanks so much for your work. Let me know if I can help.

**Comment by maxatome** [comment]
Thank you very much @stewi1014 for reporting this bug and providing the test case.

#102 should fix this issue. Could you check in you environment, before I merge?

**Comment by maxatome** [comment]
Merged. I will create a new release before the end of the week.

**Comment by maxatome** [comment]
Done: https://github.com/maxatome/go-testdeep/releases/tag/v1.7.0
Thanks again for your help @stewi1014
