### ISSUE TITLE
Recursive SubMap/SuperMap?

### ISSUE THREAD

**Issue by artem-nefedov** [maxatome/go-testdeep#105]
Is there a way to compare submaps/supermaps recursively (make sure that partial compare is propagated to nested maps)? Based on what I see, the default behavior is that only the parent map is compared partially, while all nested maps are expected to have exact match.

**Comment by maxatome** [comment]
Hi,
Do you have an example of data you want to match?

**Comment by maxatome** [comment]
Does something like https://play.golang.org/p/-NAATrt-mRv meet your need?

**Comment by artem-nefedov** [comment]
I have two yaml files.

a.yaml:
```
a: foo
b: bar
c:
  x: y
  z: 123
```

b.yaml:
```
a: foo
c:
  z: 123
```

Both of those get unmarshalled from files into maps, so I don't define `td.MapEntries{}`.
I need check to confirm that "b.yaml" is a submap of "a.yaml".

**Comment by maxatome** [comment]
You have to pre-process `a` before giving it to [`td.Cmp`](https://pkg.go.dev/github.com/maxatome/go-testdeep/td?tab=doc#Cmp), like I do with `RecursiveSubMapOf` in https://play.golang.org/p/vj_lRT8AwEU
