### ISSUE TITLE
Ignore unexported struct fields?

### ISSUE THREAD

**Issue by siadat** [maxatome/go-testdeep#146]
I want to compare all fields in two large structs, except the unexported fields. Is there any way to achieve that without manually specifying each field in a SStruct? I might be missing an operator/helper function, but the best solution that comes to my mind is to compare the JSON representation of the two structs.

Example for clarification:

```go
type X struct {
  Field1      int
  Field2      int
  Field3      int
  Field4      int
  Field5      int
  fieldIgnore int // <--- want to ignore this when doing a t.Cmp(x1, x2)
}
```

**Comment by maxatome** [comment]
Hello, you can use [`Struct`](https://go-testdeep.zetta.rocks/operators/struct/) instead of `SStruct`. Be careful that 0 values are not tested with `Struct`, you have to set them in `expectedFields` param.

Note that this feature matches the issue #23

**Comment by siadat** [comment]
Thanks! I see, so Struct solves my problem if I leave my unexported fields to have zero values. But as you said, if what I expect a field to have zero value it will be ignored by Struct.

**Comment by siadat** [comment]
I cannot know when a field might have a zero value (to use the expectedFields param), so, I think I will json marshal the structs and use the JSON helper.

**Comment by siadat** [comment]
@maxatome Btw thank you for building and maintaining this package. :) It has made my life easier by producing very readable error messages pointing out where exactly the differences are. 💌

**Comment by siadat** [comment]
@maxatome thank you for the update, I will look at it.

**Comment by siadat** [comment]
It looks very interesting and powerful! I can provide 2 opinionated comments, feel free to ignore them:

- I was wondering if the shell pattern is really necessary when we have regexp. But maybe you could let it be there for a while to see if it really adds any extra value.
- It took me a while to understand what the numbers meant (the order in which the matchers are matched). Maybe because the equal/unequal operator kinda look similar to an infix binary operator (ie "operand1 InfixOperator operand2").

**Comment by maxatome** [comment]
1. I agree, but shell patterns have the advantage to be simpler to write than regexp (for the ones who don't masterize regexps), that is why I chose to propose both;
2. it was important to specify an order, as well as not to require it. So use it as an optional prefix seemed a not so bad idea. But I understand the possible confusion.

I reopen the issue as I will soon propose a solution for it without having to rely on Struct/SStruct operators.

**Comment by maxatome** [comment]
Hi @siadat, please have a look at #154. It should definitively fulfill your needs :)

**Comment by siadat** [comment]
Nice! :D Currently, I'm not working on that project, but the feature looks very good, I will give it a go! 👍

**Comment by siadat** [comment]
Just wanted to let you know: today I discovered WithCmpHooks while browsing the source code, and I love it. It has been very helpful for me. I wanted to ignore all nested fields with a specific type.

Don't take my uneducated feedback too seriously, but I'll share what I'm think: I find hooks a lot easier to understand than Struct. Also hooks work on all nested fields while Struct doesn't. However, hooks (as far as I have learned so far) don't have access to the field names, they are only given their types. I was just wondering what it would look like if the hooks were prided the absolute data path as well, eg
```
"DATA.SomeSlice[0].SomeOtherSlice[2].Path.Value"
```

or some slice representing the path to the thing that is being compared

```
{"DATA", "SomeSlice", 0, "SomeOtherSlice", 2, "Path", "Value"}
```

**Comment by maxatome** [comment]
Having a "hook" for a specific path is not the philosophy of go-testdeep but more the one of go-cmp. I prefer to avoid it.

At the time of writing, [`(*td.T).WithCmpHooks`](https://pkg.go.dev/github.com/maxatome/go-testdeep/td#T.WithCmpHooks) method accepts 2 kinds of hooks:
```
func (got A, expected A) bool
func (got A, expected A) error
```
we can allow 2 others:
```
func (got A, expected A, path string) bool
func (got A, expected A, path string) error
```
`path` as a string, or exposing internal types used for paths (see https://github.com/maxatome/go-testdeep/blob/master/internal/ctxerr/path.go#L18) with some useful new methods?

If it is a really needed feature, could you please open a new issue? so it can be discussed in non-hidden mode :)

**Comment by siadat** [comment]
Yes, something like this:

```
func (got A, expected A, path td.Path) bool
func (got A, expected A, path td.Path) error
```
or maybe something like this:
```
func (t *T) WithCmpHooksFiltered(filter td.PathFilter, func(got A, expected A) bool)
func (t *T) WithCmpHooksFiltered(filter td.PathFilter, func(got A, expected A) error)
```

But I don't really need this feature at the moment, I don't have a specific use-case for it in mind! It was just a curious idea. :)
