### ISSUE TITLE
remove Run method from TF interface

### ISSUE THREAD

**Issue by rogpeppe** [maxatome/go-testdeep#99]
The `TestingFT` interface includes the Run method, which uses the `*testing.T` parameter directly, which means that go-testdeep cannot be used with `*testing.B` or alongside other testing helper packages such as [quicktest](https://github.com/frankban/quicktest).

If you embed `testing.TB` inside `T` instead of defining your own `testingFT` interface, this problem goes away, and additionally you can take advantage of new features added to `testing.TB` ([Cleanup](https://golang.org/pkg/testing/#T.Cleanup) for example) automatically and without breaking your API by adding methods to an interface type.

**Comment by maxatome** [comment]
I like the idea, let me test on my side :) Thanks for the report.

**Comment by maxatome** [comment]
Done in [`tb`](https://github.com/maxatome/go-testdeep/compare/master...tb) branch.
I replaced the `td.TestingFT` interface by `testing.TB` as you suggested and `RunT()` method correctly delegates to any `T.Run(string, func(T)) bool` method.
I need to sleep a little to check all is OK: shouldn't I keep `td.TestingFT` as an alias of `testing.TB` instead?
Anyway, this `Run()` function bored me for a long time, thank you for pushing me to enhance this part. :)

**Comment by rogpeppe** [comment]
Thanks for doing this!

A good reason to keep `testing.FT` around as an alias would be to preserve backward compatibility, but since you would already be breaking compatibility by removing the `Run` method, maybe that's not worth doing. It depends a bit on how you see the maturity of this module and how many existing importers you think the change might break.

**Comment by maxatome** [comment]
Done in #100 + [v1.6.0](https://github.com/maxatome/go-testdeep/releases/tag/v1.6.0) release.

I ended up choosing to let `testing.FT` interface as a deprecated alias on `testing.TB`.

Thanks!
